name: DNS Resolution

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:        # 支持手动触发

# 定义工作流所需的权限
permissions:
  contents: write    # 允许写入仓库内容（用于提交文件）
  issues: write     # 允许创建Issues（用于通知）

jobs:
  resolve:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run DNS resolver
        env:
          API_URL_REGIONS: ${{ secrets.API_URL_REGIONS }}
          DOMAIN_SUFFIX: ${{ secrets.DOMAIN_SUFFIX }}
          DNS_SERVER: ${{ secrets.DNS_SERVER }}
          DNS_TIMEOUT: ${{ secrets.DNS_TIMEOUT }}
        run: python 1.py
      
      # 提交和推送更改
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add ip_list.txt
          if ! git diff --quiet HEAD || ! git diff --staged --quiet; then
            git commit -m "Update IP list [skip ci]"
            git push origin HEAD:${GITHUB_REF}
          else
            echo "No changes to commit"
          fi
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ip-list
          path: ip_list.txt
          retention-days: 7
          compression-level: 6
      
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet HEAD^ HEAD ip_list.txt || echo "changes=true" >> $GITHUB_OUTPUT
      
      # 使用GITHUB_TOKEN创建Issue进行失败通知
      - name: Send notification on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'DNS Resolution Failed',
              body: `DNS resolution workflow failed at ${new Date().toISOString()}\nPlease check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`
            })
      
      # 使用GITHUB_TOKEN创建Issue进行更新通知
      - name: Send notification on IP changes
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'IP List Updated',
              body: `IP list has been updated at ${new Date().toISOString()}\nCheck the [latest changes](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/commits/main/ip_list.txt).`
            }) 
