name: DNS解析自动更新

on:
  schedule:
    - cron: '30 0,8,16 * * *'  # 每天北京时间08:30、16:30、00:30运行（UTC 00:30、08:30、16:30）
  workflow_dispatch:  # 支持手动触发

permissions:
  contents: write
  issues: write

jobs:
  dns-resolution:
    runs-on: ubuntu-22.04
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install dnspython python-dotenv
        
    - name: 运行DNS解析
      env:
        API_URL_REGIONS: ${{ secrets.API_URL_REGIONS }}
        DOMAIN_SUFFIX: ${{ secrets.DOMAIN_SUFFIX }}
        DNS_SERVER: ${{ secrets.DNS_SERVER }}
        DNS_TIMEOUT: ${{ secrets.DNS_TIMEOUT }}
      run: |
        echo "=== 环境检查 ==="
        echo "Python版本:"
        python --version
        echo "工作目录:"
        pwd
        ls -la
        
        echo -e "\n=== 环境变量检查 ==="
        echo "API_URL_REGIONS: ${API_URL_REGIONS:+已设置}"
        echo "DOMAIN_SUFFIX: ${DOMAIN_SUFFIX:+已设置}"
        echo "DNS_SERVER: ${DNS_SERVER:+已设置}"
        echo "DNS_TIMEOUT: ${DNS_TIMEOUT:+已设置}"
        
        echo -e "\n=== 开始执行DNS解析 ==="
        # 使用-u参数确保Python输出不被缓存
        python -u 1.py
        
        echo -e "\n=== 检查执行结果 ==="
        echo "当前目录文件列表:"
        ls -la
        
        if [ -f ip_list.txt ]; then
          echo -e "\nip_list.txt已生成:"
          echo "文件大小: $(wc -c < ip_list.txt) 字节"
          echo "文件内容:"
          cat ip_list.txt
        else
          echo -e "\n错误: ip_list.txt未生成!"
          echo "可能的原因:"
          echo "1. Python脚本执行失败"
          echo "2. 配置参数不正确"
          echo "3. DNS解析失败"
          exit 1
        fi
        
    - name: 准备Git提交
      if: success() && hashFiles('ip_list.txt') != ''
      run: |
        echo "=== Git配置 ==="
        echo "配置用户信息..."
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        echo -e "\n当前Git配置:"
        git config --list
        
        echo -e "\n=== 工作目录状态 ==="
        echo "目录内容:"
        ls -la
        
        echo -e "\n查找并显示所有.gitignore文件:"
        find . -name ".gitignore" -type f -exec sh -c 'echo "=== 文件: {}"; cat {}; echo' \;
        
        echo -e "\nGit状态:"
        git status
        
        if [ -f ip_list.txt ]; then
          echo -e "\n添加ip_list.txt到暂存区..."
          echo "文件状态:"
          ls -l ip_list.txt
          
          echo -e "\n检查文件是否被忽略:"
          git check-ignore -v ip_list.txt || echo "文件未被忽略"
          
          echo -e "\n尝试强制添加文件..."
          if git add -f ip_list.txt; then
            echo "文件添加成功"
          else
            echo "强制添加失败，错误码: $?"
            exit 1
          fi
          
          echo -e "\n验证文件是否在暂存区:"
          git status
          if git diff --cached --quiet ip_list.txt; then
            echo "错误：文件未被添加到暂存区"
            exit 1
          else
            echo "文件已成功添加到暂存区"
          fi
        else
          echo "错误: ip_list.txt不存在!"
          exit 1
        fi
        
    - name: 检查变更
      id: check
      if: success()
      run: |
        echo "=== 检查文件变更 ==="
        if git diff --cached --quiet; then
          echo "没有需要提交的更改"
        else
          echo "发现更改，准备提交"
          echo "changes=true" >> $GITHUB_OUTPUT
          echo -e "\n更改内容:"
          git diff --cached
        fi
        
    - name: 提交并推送更改
      if: steps.check.outputs.changes == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "=== 提交更改 ==="
        git commit -m "Update IP list" || {
          echo "提交失败，错误码: $?"
          exit 1
        }
        
        echo -e "\n=== 推送到仓库 ==="
        # 确保我们有最新的更改
        git pull --rebase origin ${GITHUB_REF#refs/heads/}
        
        # 推送更改
        git push origin HEAD:${GITHUB_REF#refs/heads/} || {
          echo "推送失败，错误码: $?"
          echo "远程仓库信息:"
          git remote -v
          exit 1
        }
        
        # 简单验证推送是否成功
        echo -e "\n=== 验证推送结果 ==="
        git fetch origin
        LOCAL_COMMIT=$(git rev-parse HEAD)
        REMOTE_COMMIT=$(git rev-parse origin/${GITHUB_REF#refs/heads/})
        
        if [ "$LOCAL_COMMIT" = "$REMOTE_COMMIT" ]; then
          echo "成功推送到仓库"
          echo "本地提交: $LOCAL_COMMIT"
          echo "远程提交: $REMOTE_COMMIT"
        else
          echo "推送验证失败!"
          echo "本地提交: $LOCAL_COMMIT"
          echo "远程提交: $REMOTE_COMMIT"
          exit 1
        fi
        
    - name: 上传结果文件
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: ip-list
        path: ip_list.txt
        compression-level: 6 
